services:
  myclienti:
    image: myclienti-clienti
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myclienti
    restart: always
    ports:
      - "3034:3034"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
      - CLIENTI_API_KEY=${CLIENTI_API_KEY}
    networks:
      - mysagra_default

networks:
  mysagra_default:
    external: true